version: '3.0'
services:

#  sqlserver:
#    image: microsoft/mssql-server-linux:latest
#    ports: 
#    - 1433:1433
#    expose:
#    - 1433
#    environment:
#    - ACCEPT_EULA=Y
#    - SA_PASSWORD=password
#    volumes:
#    - ./data/sqlserver:/var/opt/mssql

  mysql:
    image: mysql:5.7.17
    volumes:
    - ./data/mysql:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=mypassword
    - MYSQL_DATABASE=myapp
    ports:
    - 3306:3306
    expose:
    - 3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOST=mysql
    - PMA_USER=root
    - PMA_PASSWORD=mypassword
    ports:
    - 8080:80
    volumes:
    - ./data/phpmyadminsessions:/sessions
